### ISSUE TITLE
island within a hole as a single polygon

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/earcut#96] opened 2018-03-09 00:21 UTC
Using https://gist.github.com/andrewharvey/ee7d9b91c182dce34f96d0dbcd19bb29 in the earcut vis results in 

![earcut](https://user-images.githubusercontent.com/117278/37183738-acb5a69a-238b-11e8-9390-332b8db91c93.png)

the inside should be filled in like this:

![leaflet](https://user-images.githubusercontent.com/117278/37183743-b9ae2d68-238b-11e8-9d4f-666a77a6de0c.png)

ref https://github.com/mapbox/mapbox-gl-js/issues/3545#issuecomment-371671017

**Comment by andrewharvey** [comment] 2018-03-09 02:06
So it seems this has nothing to do with the touching point, but rather an island within a hole of a polygon isn't accepted.

**Comment by mourner** [comment] 2018-03-09 06:34
Duplicate of https://github.com/mapbox/earcut/issues/94 — please see the explanation there.

**Closed by mourner** 2018-03-09 06:34 UTC

**Comment by andrewharvey** [comment] 2018-03-09 07:32
Thank you!
