### ISSUE TITLE
Triagulation doesn't work when polygon is vertical

### ISSUE THREAD

**Issue by chopper** [mapbox/earcut#59] opened 2016-03-28 08:03 UTC
The triangulation comes back as an empty array if the vertices of the polygon are in a vertical plane, e.g. 
```
polygon = [0,0,0,  1,0,1,  2,0,0]
earcut['default'](polygon, null, 3)
````
will return `[]`

**Comment by tmcw** [comment] 2016-03-28 12:42
Duplicate of #21

**Closed by tmcw** 2016-03-28 12:42 UTC
