### ISSUE TITLE
Holes and T-junctions?

### ISSUE THREAD

**Issue by samsonsite1** [mapbox/earcut#105] opened 2018-09-08 21:14 UTC
Can mapbox earcut completely eliminate T-junctions?
I have an issue where triangulating a polygon with holes is creating T-junctions.

For data:
https://github.com/mapbox/earcut/issues/104

One of the main reasons why I was looking for a poly tesselator, is to create a triangulation without T-junctions.  This is when the vertex lies against an edge, but doesn't connect.

Thanks.

![t_junctions](https://user-images.githubusercontent.com/7414478/45258706-fd954d80-b3ab-11e8-8771-e82982735f80.PNG)

**Comment by mrgreywater** [comment] 2018-09-08 21:31
You could potentially detect those T junction edges in the function [earcutLinked](https://github.com/mapbox/earcut/blob/master/src/earcut.js#L88), and avoid cutting ears on them in the first pass. This is an unusual feature though, and probably not something that won't be implemented in the project.

**Comment by samsonsite1** [comment] 2018-09-08 22:03
Thanks for looking at it.  I will have to give the issue more thought.

**Comment by samsonsite1** [comment] 2018-09-09 05:13
I think you're correct.  I should explain my application also goes beyond just rendering.  T-junctions are cracks in the model,  it prevents certain edge traversing algorithms from functioning properly.

**Comment by mourner** [comment] 2018-09-09 07:46
Let's close as a duplicate of #74

**Closed by mourner** 2018-09-09 07:46 UTC

**Comment by mrgreywater** [comment] 2018-09-09 10:56
As a workaround, In case you are sure your polygons are simple, and you're fine with loosing some robustness, you can comment out the `area(p.prev, p, p.next) === 0` in [filterPoints](https://github.com/mapbox/earcut/blob/master/src/earcut.js#L73) so those colinear points are not removed.

**Comment by samsonsite1** [comment] 2018-09-09 16:45
Thanks, does earcut behave more like GLUtessellator when degenerate triangles are kept?

I used GLUtessellator before, and technically, I would say it doesn't create T-junctions.  But, if you run the triangulated polygon through a mesh cleaner that removes degen trigs, T-junctions are created.  This is because degen trigs were inserted in the edges during triangulation, which somewhat fixed the issue, but not in the best way.
